FROM 903921708000.dkr.ecr.ap-northeast-1.amazonaws.com/raspios-lite-arm64-runs-on-x86-64:latest

ADD go1.19.5.linux-arm64.tar.gz /usr/local

RUN apt update -y && \
    apt install -y pcscd libpcsclite1 libpcsclite-dev

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV GOCACHE=/src/.cache
